print("Let's turn you into a 1337 H4x0r.")
string = input("Please enter some text: ")
string = string.replace("a", "4")
string = string.replace("b", "8")
string = string.replace("e", "3")
string = string.replace("l", "1")
string = string.replace("o", "0")
string = string.replace("s", "5")
string = string.replace("t", "7")
print("If you were a 1337 Hax0r, you would have said it like this:")
print(string)
